- name: begehung
  color: 1f77b4
- name: neu
  color: cccccc
- name: mangel/gering
  color: c3e6cb
- name: mangel/mittel
  color: ffd166
- name: mangel/hoch
  color: f4a261
- name: mangel/kritisch
  color: e76f51
- name: status/offen
  color: d3d3d3
- name: status/in_bearbeitung
  color: 87ceeb
- name: status/behoben
  color: 2ca02c
- name: kategorie/psa
  color: 6a5acd
- name: kategorie/verkehrswege
  color: 17becf
- name: kategorie/maschinen
  color: 9467bd
