# =========================
# 1) CHECKLISTE (mit Fotos)
# =========================

- type: markdown
  attributes:
    value: "## 1. Checkliste"

# --- PSA & Zutritt ---
- type: dropdown
  id: status_psa
  attributes:
    label: PSA & Zutritt
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_psa
  attributes:
    label: PSA & Zutritt – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_psa
  attributes:
    label: PSA & Zutritt – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**. Mehrere Fotos nacheinander möglich."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Ordnung & Sauberkeit ---
- type: dropdown
  id: status_ord
  attributes:
    label: Ordnung & Sauberkeit
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_ord
  attributes:
    label: Ordnung & Sauberkeit – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_ord
  attributes:
    label: Ordnung & Sauberkeit – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Verkehrswege & Absperrungen ---
- type: dropdown
  id: status_verkehr
  attributes:
    label: Verkehrswege & Absperrungen
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_verkehr
  attributes:
    label: Verkehrswege & Absperrungen – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_verkehr
  attributes:
    label: Verkehrswege & Absperrungen – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Erdarbeiten / Gräben / Wasserbau ---
- type: dropdown
  id: status_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Gerüste & Leitern ---
- type: dropdown
  id: status_gerueste
  attributes:
    label: Gerüste & Leitern
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_gerueste
  attributes:
    label: Gerüste & Leitern – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_gerueste
  attributes:
    label: Gerüste & Leitern – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Krane & Hebezeuge / Anschlagmittel ---
- type: dropdown
  id: status_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Maschinen & Geräte (inkl. Teleskopstapler) ---
- type: dropdown
  id: status_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler)
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler) – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler) – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Elektrik & Beleuchtung ---
- type: dropdown
  id: status_elektrik
  attributes:
    label: Elektrik & Beleuchtung
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_elektrik
  attributes:
    label: Elektrik & Beleuchtung – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_elektrik
  attributes:
    label: Elektrik & Beleuchtung – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false


# --- Gefahrstoffe / Umweltschutz ---
- type: dropdown
  id: status_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz
    options:
      - OK
      - Hinweis
      - Mangel
      - n.a.
  validations:
    required: false

- type: textarea
  id: bemerk_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …\nFoto 2 …"
  validations:
    required: false
