name: "Baustellenbegehung"
description: "Formular zur Erfassung einer Baustellenbegehung – inklusive Fotodokumentation und automatischem PDF-Bericht."
title: "[Begehung] Projektname – Datum"
labels:
  - begehung
body:

# ======================
# 0) Allgemeine Angaben
# ======================

- type: markdown
  attributes:
    value: |
      ## Baustellenbegehung
      Bitte alle relevanten Felder ausfüllen. Fotos können direkt mit dem Smartphone aufgenommen und eingefügt werden.

- type: input
  id: ort
  attributes:
    label: Ort / Baustelle
    placeholder: "z. B. Köln-Deutz, Baustelle Wehr XYZ"
  validations:
    required: true

- type: input
  id: datum
  attributes:
    label: Datum
    placeholder: "JJJJ-MM-TT"
  validations:
    required: true

- type: input
  id: sifa
  attributes:
    label: Sifa / Ersteller
    placeholder: "Name der Fachkraft"
  validations:
    required: true

- type: textarea
  id: wetter
  attributes:
    label: Wetterbedingungen
    placeholder: "z. B. bewölkt, 15 °C, leicht windig"
  validations:
    required: false

# ======================
# 1) Checkliste mit Fotos
# ======================

- type: markdown
  attributes:
    value: "## 1. Checkliste"

# --- PSA & Zutritt ---
- type: dropdown
  id: status_psa
  attributes:
    label: PSA & Zutritt
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_psa
  attributes:
    label: PSA & Zutritt – Bemerkungen
    placeholder: "Kurzbeschreibung, Beobachtungen …"
  validations:
    required: false

- type: textarea
  id: fotos_psa
  attributes:
    label: PSA & Zutritt – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
    placeholder: "Foto 1 …"
  validations:
    required: false


# --- Ordnung & Sauberkeit ---
- type: dropdown
  id: status_ord
  attributes:
    label: Ordnung & Sauberkeit
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_ord
  attributes:
    label: Ordnung & Sauberkeit – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_ord
  attributes:
    label: Ordnung & Sauberkeit – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Verkehrswege & Absperrungen ---
- type: dropdown
  id: status_verkehr
  attributes:
    label: Verkehrswege & Absperrungen
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_verkehr
  attributes:
    label: Verkehrswege & Absperrungen – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_verkehr
  attributes:
    label: Verkehrswege & Absperrungen – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Erdarbeiten / Gräben / Wasserbau ---
- type: dropdown
  id: status_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_erd
  attributes:
    label: Erdarbeiten / Gräben / Wasserbau – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Gerüste & Leitern ---
- type: dropdown
  id: status_gerueste
  attributes:
    label: Gerüste & Leitern
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_gerueste
  attributes:
    label: Gerüste & Leitern – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_gerueste
  attributes:
    label: Gerüste & Leitern – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Krane & Hebezeuge / Anschlagmittel ---
- type: dropdown
  id: status_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_krane
  attributes:
    label: Krane & Hebezeuge / Anschlagmittel – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Maschinen & Geräte (inkl. Teleskopstapler) ---
- type: dropdown
  id: status_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler)
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler) – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_maschinen
  attributes:
    label: Maschinen & Geräte (inkl. Teleskopstapler) – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Elektrik & Beleuchtung ---
- type: dropdown
  id: status_elektrik
  attributes:
    label: Elektrik & Beleuchtung
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_elektrik
  attributes:
    label: Elektrik & Beleuchtung – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_elektrik
  attributes:
    label: Elektrik & Beleuchtung – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# --- Gefahrstoffe / Umweltschutz ---
- type: dropdown
  id: status_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz
    options: [OK, Hinweis, Mangel, n.a.]
  validations:
    required: false

- type: textarea
  id: bemerk_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz – Bemerkungen
  validations:
    required: false

- type: textarea
  id: fotos_gefahr
  attributes:
    label: Gefahrstoffe / Umweltschutz – Fotos/Nachweise
    description: "Tippe hier hinein und wähle **Foto aufnehmen** / **Datei auswählen**."
  validations:
    required: false


# ======================
# 2) Zusammenfassung / Freitext
# ======================

- type: markdown
  attributes:
    value: "## 2. Zusammenfassung"

- type: textarea
  id: zusammenfassung
  attributes:
    label: Gesamteindruck / Hinweise / Maßnahmen
    placeholder: "Freitext – Gesamte Bewertung oder wichtige Punkte"
  validations:
    required: false

