name: Build Begehungsbericht
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  actions: read

jobs:
  build-report:
    if: contains(github.event.label.name, 'begehung')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hole Issue Body via API
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            ${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            | jq -r '.body' > issue_body.md

      - name: Install pandoc + LaTeX + Python
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended \
            texlive-latex-extra jq curl python3

      - name: Render Markdown aus Issue (Tabellen)
        run: |
          python3 scripts/render_report.py

      - name: PDF bauen (Logo in Kopfzeile, jede Seite)
        run: |
          mkdir -p reports
          pandoc report.md \
            --from=gfm \
            --template=docs/template.latex \
            --pdf-engine=pdflatex \
            -o reports/begehung-${{ github.event.issue.number }}.pdf

      - name: Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: begehung-${{ github.event.issue.number }}.pdf
          path: reports/begehung-${{ github.event.issue.number }}.pdf

