name: Build Begehungsbericht

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  build:
    if: github.event.label.name == 'begehung'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write issue body to file
        run: |
          cat > issue_body.md <<'EOF'
          ${{ github.event.issue.body }}
          EOF

      - name: Install pandoc + LaTeX + Python
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc python3 \
            texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended fonts-lmodern

      - name: Render markdown from issue (tables)
        run: |
          python3 scripts/render_report.py

   - name: Build PDF (immer mit Debug)
  run: |
    mkdir -p reports

    echo "==> Schritt 1: Debug-LaTeX-Datei erzeugen"
    pandoc report.md \
      --from=markdown+raw_tex+pipe_tables \
      --template=docs/template.latex \
      --resource-path=".:docs" \
      -t latex \
      -o "reports/debug-${{ github.event.issue.number }}.tex"

    echo "==> Schritt 2: PDF erzeugen (Fehler werden ignoriert)"
    set +e
    pandoc report.md \
      --from=markdown+raw_tex+pipe_tables \
      --template=docs/template.latex \
      --pdf-engine=pdflatex \
      --resource-path=".:docs" \
      -o "reports/begehung-${{ github.event.issue.number }}.pdf"
    echo "Pandoc exit code: $?"
    set -e

- name: Upload artifacts (auch bei Fehler)
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: begehung-${{ github.event.issue.number }}
    path: |
      reports/debug-${{ github.event.issue.number }}.tex
      reports/begehung-${{ github.event.issue.number }}.pdf
    if-no-files-found: warn
